// <auto-generated />
using System;
using LightMasterMVVM.DbAssets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LightMasterMVVM.Migrations
{
    [DbContext(typeof(ScoutingContext))]
    [Migration("20200918183053_Tablets")]
    partial class Tablets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LightMasterMVVM.Models.FRCTeamModel", b =>
                {
                    b.Property<int>("team_instance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("event_key")
                        .HasColumnType("text");

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.Property<string>("rated_tier")
                        .HasColumnType("text");

                    b.Property<int>("team_number")
                        .HasColumnType("integer");

                    b.HasKey("team_instance_id");

                    b.ToTable("FRCTeams");
                });

            modelBuilder.Entity("LightMasterMVVM.Models.TBA_DB_Model", b =>
                {
                    b.Property<string>("key")
                        .HasColumnType("text");

                    b.Property<string>("event_key")
                        .HasColumnType("text");

                    b.Property<bool>("isqualifying")
                        .HasColumnType("boolean");

                    b.Property<int>("match_number")
                        .HasColumnType("integer");

                    b.Property<string>("rawjson")
                        .HasColumnType("text");

                    b.HasKey("key");

                    b.ToTable("TBAMatches");
                });

            modelBuilder.Entity("LightMasterMVVM.Models.TabletInstance", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<int>("AuthenticationLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DiagnosticReportReceived")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastCommunicated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastKnownBattery")
                        .HasColumnType("integer");

                    b.Property<string>("TabletName")
                        .HasColumnType("text");

                    b.HasKey("Identifier");

                    b.ToTable("TabletInstances");
                });

            modelBuilder.Entity("LightMasterMVVM.Models.TeamMatch", b =>
                {
                    b.Property<int>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("APIAccuracy")
                        .HasColumnType("integer");

                    b.Property<bool>("APIChecked")
                        .HasColumnType("boolean");

                    b.Property<bool>("A_InitiationLine")
                        .HasColumnType("boolean");

                    b.Property<int[]>("AlliancePartners")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("ClientLastSubmitted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("ClientSubmitted")
                        .HasColumnType("boolean");

                    b.Property<int>("CycleTime")
                        .HasColumnType("integer");

                    b.Property<bool>("DefenseAgainst")
                        .HasColumnType("boolean");

                    b.Property<bool>("DefenseFor")
                        .HasColumnType("boolean");

                    b.Property<int>("DisabledSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("E_Balanced")
                        .HasColumnType("boolean");

                    b.Property<bool>("E_ClimbAttempt")
                        .HasColumnType("boolean");

                    b.Property<bool>("E_ClimbSuccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("E_Park")
                        .HasColumnType("boolean");

                    b.Property<string>("EventCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsQualifying")
                        .HasColumnType("boolean");

                    b.Property<int[]>("LoadCoordinates")
                        .HasColumnType("integer[]");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<int>("NumCycles")
                        .HasColumnType("integer");

                    b.Property<int[]>("PowerCellInner")
                        .HasColumnType("integer[]");

                    b.Property<int[]>("PowerCellLower")
                        .HasColumnType("integer[]");

                    b.Property<int[]>("PowerCellMissed")
                        .HasColumnType("integer[]");

                    b.Property<int[]>("PowerCellOuter")
                        .HasColumnType("integer[]");

                    b.Property<string>("RobotPosition")
                        .HasColumnType("text");

                    b.Property<string>("ScoutName")
                        .HasColumnType("text");

                    b.Property<int[]>("ShotCoordinates")
                        .HasColumnType("integer[]");

                    b.Property<bool>("T_ControlPanelPosition")
                        .HasColumnType("boolean");

                    b.Property<bool>("T_ControlPanelRotation")
                        .HasColumnType("boolean");

                    b.Property<string>("TabletId")
                        .HasColumnType("text");

                    b.Property<string[]>("TapLogs")
                        .HasColumnType("text[]");

                    b.Property<string>("TeamName")
                        .HasColumnType("text");

                    b.Property<int>("team_instance_id")
                        .HasColumnType("integer");

                    b.HasKey("MatchID");

                    b.HasIndex("team_instance_id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LightMasterMVVM.Models.TeamMatch", b =>
                {
                    b.HasOne("LightMasterMVVM.Models.FRCTeamModel", "TrackedTeam")
                        .WithMany("TeamMatches")
                        .HasForeignKey("team_instance_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
